SELECT
    B.AUTHOR_ID AS AUTHOR_ID,
    A.AUTHOR_NAME AS AUTHOR_NAME,
    B.CATEGORY AS CATEGORY,
    SUM(B.PRICE*BS.SALES) AS TOTAL_SALES
FROM
    (
    SELECT
        BOOK_ID,
        SALES
    FROM
        BOOK_SALES
    WHERE
        DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'    
    ) AS BS
INNER JOIN
    BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
INNER JOIN
    AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY
    B.AUTHOR_ID,B.CATEGORY,A.AUTHOR_NAME
ORDER BY
    AUTHOR_ID ASC,
    CATEGORY DESC