-- 코드를 작성해주세요

# PARENT_ITEM_ID에 값이 없는 것을 찾아라

SELECT
    A.ITEM_ID,
    A.ITEM_NAME,
    A.RARITY
FROM
    ITEM_INFO AS A
LEFT JOIN
    ITEM_TREE AS B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE
    B.PARENT_ITEM_ID IS NULL
ORDER BY
    A.ITEM_ID DESC