SELECT
    # A. DATETIME,
    # B. DATETIME,
    A.ANIMAL_ID AS ANIMAL_ID,
    A.NAME AS NAME
    # B.DATETIME-A.DATETIME AS DATETIME
    
FROM
    ANIMAL_INS AS A
INNER JOIN
    ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID

ORDER BY
    B.DATETIME - A.DATETIME DESC

LIMIT 2