# SELECT
#     *,
#     A.FISH_NAME,
#     B.FISH_COUNT
# FROM
#     FISH_NAME_INFO AS A
# INNER JOIN
#     (
#     SELECT
#         FISH_TYPE,
#         COUNT(FISH_TYPE) AS FISH_COUNT
#     FROM
#         FISH_INFO
#     GROUP BY
#         FISH_TYPE    
#     ) AS B ON A.FISH_TYPE = B.FISH_TYPE
# ORDER BY
#     B.FISH_COUNT DESC;
    
SELECT
    COUNT(B.FISH_NAME) AS FISH_COUNT,
    B.FISH_NAME AS FISH_NAME
    
FROM
    FISH_INFO AS A
INNER JOIN
    FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY
    B.FISH_NAME
ORDER BY
    FISH_COUNT DESC
