SELECT
    A.PRODUCT_ID AS PRODUCT_ID,
    A.PRODUCT_NAME AS PRODUCT_NAME,
    A.PRICE * B.SUM_AMOUNT AS TOTAL_SALES
FROM
    FOOD_PRODUCT AS A
INNER JOIN
    (
    SELECT
        PRODUCT_ID,
        SUM(AMOUNT) AS SUM_AMOUNT
    FROM 
        FOOD_ORDER
    WHERE
        DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
    GROUP BY
        PRODUCT_ID
    ) AS B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID ASC
