SELECT 
    A.FLAVOR
FROM
    FIRST_HALF AS A
LEFT OUTER JOIN
    (
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS SUM_TOTAL_ORDER
    FROM
        JULY
    GROUP BY
        FLAVOR
    ) AS B ON A.FLAVOR = B.FLAVOR
ORDER BY
    IF(
        B.SUM_TOTAL_ORDER IS NULL,
        A.TOTAL_ORDER,
        A.TOTAL_ORDER + B.SUM_TOTAL_ORDER
    ) DESC
LIMIT 3