SELECT
    A.hour,
    CASE 
        WHEN B.hour IS NULL THEN 0
        ELSE B.count
    END AS COUNT
FROM (
    SELECT 0 AS HOUR FROM DUAL UNION ALL
    SELECT 1 AS HOUR FROM DUAL UNION ALL
    SELECT 2 AS HOUR FROM DUAL UNION ALL
    SELECT 3 AS HOUR FROM DUAL UNION ALL
    SELECT 4 AS HOUR FROM DUAL UNION ALL
    SELECT 5 AS HOUR FROM DUAL UNION ALL
    SELECT 6 AS HOUR FROM DUAL UNION ALL
    SELECT 7 AS HOUR FROM DUAL UNION ALL
    SELECT 8 AS HOUR FROM DUAL UNION ALL
    SELECT 9 AS HOUR FROM DUAL UNION ALL
    SELECT 10 AS HOUR FROM DUAL UNION ALL
    SELECT 11 AS HOUR FROM DUAL UNION ALL
    SELECT 12 AS HOUR FROM DUAL UNION ALL
    SELECT 13 AS HOUR FROM DUAL UNION ALL
    SELECT 14 AS HOUR FROM DUAL UNION ALL
    SELECT 15 AS HOUR FROM DUAL UNION ALL
    SELECT 16 AS HOUR FROM DUAL UNION ALL
    SELECT 17 AS HOUR FROM DUAL UNION ALL
    SELECT 18 AS HOUR FROM DUAL UNION ALL
    SELECT 19 AS HOUR FROM DUAL UNION ALL
    SELECT 20 AS HOUR FROM DUAL UNION ALL
    SELECT 21 AS HOUR FROM DUAL UNION ALL
    SELECT 22 AS HOUR FROM DUAL UNION ALL
    SELECT 23 AS HOUR FROM DUAL
) A
LEFT OUTER JOIN (
    SELECT
        TO_NUMBER(TO_CHAR(datetime, 'HH24')) AS HOUR,
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY
        TO_NUMBER(TO_CHAR(datetime, 'HH24'))
) B  
    ON A.hour = B.hour
ORDER BY
    A.hour ASC