-- 코드를 입력하세요

-- 회원의 ID, 이름, 성별, 생년월일
SELECT A.MEMBER_ID
     , A.MEMBER_NAME
     , A.GENDER
     , TO_CHAR(A.DATE_OF_BIRTH, 'YYYY-MM-DD')
  FROM MEMBER_PROFILE A
 WHERE TO_CHAR(A.DATE_OF_BIRTH, 'MM') = '03'
   AND A.GENDER = 'W'
   AND A.TLNO IS NOT NULL
ORDER BY A.MEMBER_ID ASC;