SELECT
    TO_NUMBER(TO_CHAR(datetime, 'HH24')) AS HOUR,
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE
    TO_CHAR(datetime, 'HH24:MM') >= '09:00' AND
    TO_CHAR(datetime, 'HH24:MM') <= '19:59'
GROUP BY
    TO_NUMBER(TO_CHAR(datetime, 'HH24'))
ORDER BY
    HOUR ASC