SELECT A.MEMBER_NAME
     , B.REVIEW_TEXT
     , TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD')
  FROM MEMBER_PROFILE A
       RIGHT OUTER JOIN REST_REVIEW B
       ON A.MEMBER_ID = B.MEMBER_ID  
 WHERE B.MEMBER_ID IN (
    SELECT MEMBER_ID
      FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)
          FROM (
                SELECT COUNT(*) AS CNT
                  FROM REST_REVIEW
                GROUP BY MEMBER_ID
               )
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT
