SELECT
    ED1.ID AS ID,
    # ED1.PARENT_ID,
    ED1.GENOTYPE AS GENOTYPE,
    # ED2.ID,
    ED2.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA AS ED1
INNER JOIN
    ECOLI_DATA AS ED2 ON ED1.PARENT_ID = ED2.ID
WHERE
    ED1.GENOTYPE & ED2.GENOTYPE = ED2.GENOTYPE
ORDER BY
    ED1.ID ASC