SELECT DISTINCT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM
    DEVELOPERS AS D    
INNER JOIN
    SKILLCODES AS SC ON SC.CODE & D.SKILL_CODE != 0
WHERE
    SC.NAME = 'Python' OR SC.NAME = 'C#'
ORDER BY   
    D.ID ASC