
SELECT
    CED.DF_DD_Y+0 AS YEAR,
    CED.M_SOC - ED2.SIZE_OF_COLONY AS YEAR_DEV,
    ED2.ID AS ID
FROM
    ECOLI_DATA AS ED2
INNER JOIN
    (
    SELECT
        DATE_FORMAT(DIFFERENTIATION_DATE,'%Y') AS DF_DD_Y,
        MAX(SIZE_OF_COLONY) AS M_SOC
    FROM
        ECOLI_DATA AS ED
    GROUP BY
        DATE_FORMAT(DIFFERENTIATION_DATE,'%Y')    
    ) AS CED ON DATE_FORMAT(ED2.DIFFERENTIATION_DATE,'%Y') = CED.DF_DD_Y
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC

