SELECT
    A.ID AS ID,
    C.FISH_NAME AS FISH_NAME,
    B.MAX_LENGTH AS LENGTH
FROM
    FISH_INFO AS A
INNER JOIN
    (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM
        FISH_INFO
    GROUP BY
        FISH_TYPE    
    ) AS B ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.MAX_LENGTH
INNER JOIN
    FISH_NAME_INFO AS C ON A.FISH_TYPE = C.FISH_TYPE
ORDER BY
    A.ID ASC
