-- 코드를 입력하세요

-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
SELECT A.TITLE
     , A.BOARD_ID
     , B.REPLY_ID
     , B.WRITER_ID
     , B.CONTENTS
     , TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD')
  FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_REPLY B ON A.BOARD_ID = B.BOARD_ID
 WHERE TO_CHAR(A.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;